
= image:https://travis-ci.org/ScrummyB3ars/spring-api.svg?branch=master["Build Status", link="https://travis-ci.org/ScrummyB3ars/spring-api"]

= Api-Toddlr

This is the api used in the toddlr-project, it handles all the database requests needed.

== Available requests

=== Subscribers

==== GET-request

----
https://api-toddlr.herokuapp.com/subscribers
----

and responds with a link:/understanding/JSON[JSON] representation of all the subscribers:

[source,json]
----
{"id":1,"facebook_id":"05245486","age_group_id":0},
{"id":2,"facebook_id":"0965875","age_group_id":1}
----

You can also get the data of a single subscriber by adding its facebook_id to the path of the request

----
https://api-toddlr.herokuapp.com/subscribers/{facebook_id}
----

==== POST-request

You can POST a new subscriber via

----
https://api-toddlr.herokuapp.com/subscribers/add
----

This request expects a POST-request with Content-type: application/json and the following json-body

[source,json]
----
{"facebook_id":"1325496","age_group_id": 0}
----

It will return the new subscriber object in it's response body if the request was successful.


==== DELETE-request

You can DELETE a new via

----
https://api-toddlr.herokuapp.com/subscribers/delete
----

This request expects a DELETE-request with Content-type: application/json and the following json-body

[source,json]
----
{"facebook_id":"1325496"}
----

It will return a 201 HttpRespone ACCEPTED if succesful.


