
= image:https://travis-ci.org/ScrummyB3ars/spring-api.svg?branch=master["Build Status", link="https://travis-ci.org/ScrummyB3ars/spring-api"]

= Api-Toddlr

This is the api used in the toddlr-project, it handles all the database requests needed.

== Available requests

== Subscribers (Facebook-client)

==== GET-request

----
https://api-toddlr.herokuapp.com/subscribers
----

and responds with a link:/understanding/JSON[JSON] representation of all the subscribers:

[source,json]
----
{"id":1,"facebook_id":"05245486","age_group_id":0},
{"id":2,"facebook_id":"0965875","age_group_id":1}
----

You can also get the data of a single subscriber by adding its facebook_id to the path of the request

----
https://api-toddlr.herokuapp.com/subscribers/{facebook_id}
----

==== POST-request

You can POST a new subscriber via

----
https://api-toddlr.herokuapp.com/subscribers/add
----

This request expects a POST-request with Content-type: application/json and the following json-body

[source,json]
----
{"facebook_id":"1325496","age_group_id": 0}
----

It will return the new subscriber object in it's response body if the request was successful.


==== DELETE-request

You can DELETE a new via

----
https://api-toddlr.herokuapp.com/subscribers/delete
----

This request expects a DELETE-request with Content-type: application/json and the following json-body

[source,json]
----
{"facebook_id":"1325496"}
----

It will return a 201 HttpResponse ACCEPTED if successful.

== Users (Email-client)

==== GET-request

----
https://api-toddlr.herokuapp.com/users
----

and responds with a link:/understanding/JSON[JSON] representation of all the subscribers:

[source,json]
----
[{"id":0,"email":"e.mail@server.github","password":"supersecrethash","zip_code":6969,"role_id":0,"username":"user.name"},
{"id":1,"email":"e.mail@server.github","password":"supersecrethash","zip_code":6969,"role_id":0,"username":"user.name"},
----

You can also get the data of a single user by adding its username to the path of the request

----
https://api-toddlr.herokuapp.com/users/{username}
----

==== POST-request

You can POST a new user and add it to the db via

----
https://api-toddlr.herokuapp.com/users/add
----

This request expects a POST-request with Content-type: application/json and the following json-body

[source,json]
----
{"username":"user.name","email": "e.mail@server.github", "zip_code": 6969}
----

It will return the new subscriber object in it's response body if the request was successful.


==== DELETE-request

You can DELETE a new via

----
https://api-toddlr.herokuapp.com/users/delete
----

This request expects a DELETE-request with Content-type: application/json and the following json-body

[source,json]
----
{"id": 16}
----

It will return a 201 HttpResponse ACCEPTED if successful.

=== Tips

Two different kind of tips: interaction_tips and theme_tips

GET a random tip

----
https://api-toddlr.herokuapp.com/interaction_tips/random
https://api-toddlr.herokuapp.com/theme_tips/random
----

This returns a json-object as the following:

[source, json]
----
==== Interaction Tip
{
  "id": 14,
  "tip_content": "Geef kleuters ruim de tijd om te vertellen wat ze willen.",
  "add_rich_language": 0,
  "type_id": 1
}

==== Theme Tip
{
  "id": 12,
  "picture": "schaduw_2",
  "tip_content": "Schijnt de zon door het raam? Laat kleuters hun schaduw zoeken. Hoe maak je die?",
  "rich_language": "null",
  "circumstances": "zonnig",
  "development_goal": "WT OD 1.8. Kleuters kunnen verschillende weersomstandigheden waarnemen, vergelijken en benoemen en voorbeelden geven van de gevolgen voor zichzelf.",
  "themes_id": 0,
  "age_group_id": 0,
  "zill_goal": "OWNA 8 Natuurlijke verschijnselen en gangbare materialen waarnemen, onderzoeken en herkennen in de omgeving"
}
----

You can the whole list of tips by doing a GET-request to the following urls

----
http://api-toddlr.herokuapp.com/interaction_tips
http://api-toddlr.herokuapp.com/theme_tips
----
